# config.yaml.example - Harmoniq Configuration File
# This file allows for more structured configuration.
# Environment variables can still override these settings.

# --- Plex Connection (can also be set via .env or environment) ---
plex_url: http://192.168.101.2:32400
plex_token: B7SVN9kc-9KzxN3jLNSy
plex_music_library_names: ["Music"] # List of music library names

# --- Scheduler ---
run_interval_minutes: 1440 # For Last.fm updates
timezone: Australia/Brisbane

# --- Last.fm (can also be set via .env or environment) ---
# lastfm_api_key: YOUR_LASTFM_API_KEY
# lastfm_user: YOUR_LASTFM_USERNAME

# --- Feature Flags ---
features:
  enable_time_playlist: true
  enable_lastfm_recs: false
  enable_lastfm_charts: false

  # For "Harmoniq Flow" (Time Playlist) specific features:
  time_playlist:
    learn_from_history: true
    include_history_tracks: true
    use_sonic_expansion: true
    use_sonic_adventure: true # Default to false for now
    sonic_sort: false
  enable_playlist_covers: true

# --- Playlist Settings ---
playlists:
  # Harmoniq Flow (Time-Based)
  time_flow:
    name: "Harmoniq Flow"
    size: 100 # Overridden by PLAYLIST_SIZE_TIME if set
    # Refinements
    min_rating: 3 # 0-5 stars, for discovery/adventure tracks
    exclude_played_days: 2
    max_skip_count: 2
    # History Integration
    history_lookback_days: 90
    history_min_plays: 3
    history_min_rating: 3 # 0-5 stars, for historical tracks
    target_history_count: 50
    # Vibe Anchors
    vibe_anchor_count: 5 # Increased default
    # Sonic Expansion
    sonic_seed_tracks: 3
    similar_tracks_per_seed: 5
    sonic_max_distance: 0.45
    final_mix_ratio: 0.4
    # Sonic Sort
    sonic_sort_similarity_limit: 20
    sonic_sort_max_distance: 0.65
    # Sonic Adventure
    adventure_anchors: 10 # This is vibe_anchor_count + target_history_count
    learned_vibe:
      lookback_days: 60 # How many days of history to analyze for learning
      top_n_moods: 5    # How many top moods from history to consider
      top_m_styles: 5   # How many top styles/genres from history
      min_occurrences: 2 # Min times a mood/style must appear to be "dominant"

  # Last.fm Derived Recommendations
  lastfm_recs:
    name: "Last.fm Discovery"
    size: 30
  # Last.fm Charts
  lastfm_charts:
    name: "Last.fm Global Charts"
    size: 50

# --- Harmoniq Flow: Period Definitions ---
# Define your named day parts and their START HOUR (0-23).
# Harmoniq Flow will refresh at these times with a vibe for that period.
# Moods and Styles defined here will be used as the BASE for that period.
# If learn_from_history is true, these will be augmented by historical vibes.
# If a period from TIME_PERIOD_SCHEDULE is not defined here, Harmoniq's internal defaults will be used.
time_periods:
  - name: "EarlyMorning"
    start_hour: 5
    # moods: ["Calm", "Peaceful"] # Optional: Override Harmoniq's internal defaults
    # styles: ["Ambient", "Acoustic"]
  - name: "Morning"
    start_hour: 8
    # moods: ["Focused", "Upbeat"]
    # styles: ["Electronic", "Pop"]
  - name: "Midday"
    start_hour: 12
    moods: ["Upbeat", "Happy", "Energetic"] # Example override
    styles: ["Pop", "Rock", "Indie"]
  - name: "Afternoon"
    start_hour: 15
    # moods: ["Energetic", "Driving"]
    # styles: ["Rock", "Rap"]
  - name: "Evening"
    start_hour: 18
    # moods: ["Relaxed", "Sentimental"]
    # styles: ["Jazz", "Soul"]
  - name: "LateNight"
    start_hour: 22
    # moods: ["Atmospheric", "Mellow"]
    # styles: ["Ambient", "Trip Hop"]

# --- Playlist Cover Generation ---
enable_playlist_covers: true # This can still be in features or top level
cover_settings:
  font_file_path: "/app/harmoniq/fonts/DejaVuSans-Bold.ttf"
  output_path: "/tmp/harmoniq_cover.png"
  # Define custom colors for periods.
  # Each period needs a list of two colors: [COLOR1, COLOR2]
  # Colors can be RGB lists [R, G, B] or hex strings "#RRGGBB"
  period_colors:
    EarlyMorning: ["#3C4664", "#6478A0"] # Example: Dark blues / purples
    Morning: [[100, 150, 200], [180, 210, 230]] # Example: Lighter blues / Sky
    Midday: ["#FFC864", "#FFA050"] # Example: Oranges / Yellows
    Afternoon: [[255, 120, 80], [220, 80, 60]] # Example: Reds / Oranges
    Evening: ["#503C6E", "#8C64A0"] # Example: Purples / Dark Blues
    LateNight: ["#1E1E3C", "#464664"] # Example: Very Dark Blues / Indigos
    DefaultVibe: ["#646464", "#969696"] # Example: Greys

# --- Logging ---
log_level: "INFO" # DEBUG, INFO, WARNING, ERROR