name: Draft Next Release Notes

on:
  push:
    branches:
      - main
      - develop

jobs:
  update_release_draft:
    name: Update Release Draft
    runs-on: ubuntu-latest
    if: >
      (github.event_name == 'push' && 
        (github.ref == 'refs/heads/main' || github.ref == 'refs/heads/develop')) ||
      (github.event_name == 'pull_request' && 
        github.event.action == 'closed' && github.event.pull_request.merged == true &&
        (github.base_ref == 'refs/heads/main' || github.base_ref == 'refs/heads/develop'))

    permissions:
      contents: write
      pull-requests: write

    steps:
      - name: Draft Release Notes
        uses: release-drafter/release-drafter@v6
        with:
          config-name: release-drafter-config.yml # Ensure this file is in .github/ on your DEFAULT branch
          publish: false 
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}